### ISSUE TITLE
Reading in mutations

### ISSUE THREAD

**Issue by pekarj** [niemasd/TreeSwift#16]
Hi Niema,

The output of TreeTime lists mutations along branches, but TreeSwift does not seem to be able to read trees that include this information. Example nexus file attached. 

Is it possible to have TreeSwift read in the mutations and assign them to the child node of a branch? 

Thanks!

Best,
Jonathan

[timetree.nexus.txt](https://github.com/niemasd/TreeSwift/files/6308212/timetree.nexus.txt)

**Comment by niemasd** [comment]
Sure, thanks for pointing this out! I've found where the bug occurs (it's a bug with parsing Newick strings with multiple parameters on a given edge). I'll try to push an update with a fix ASAP

**Comment by niemasd** [comment]
Should be fixed in TreeSwift v1.1.15!

https://pypi.org/project/treeswift/1.1.15/

**Comment by pekarj** [comment]
Perfect. Thank you so much!
