### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'edge_length'

### ISSUE THREAD

**Issue by alffdtu** [niemasd/TreeSwift#17]
Hello,

I keep finding this error for some of the trees I have:
Traceback (most recent call last):
  File "/home/alfred/.local/lib/python3.6/site-packages/treeswift/Tree.py", line 1431, in read_tree_newick
    n.edge_length = float(ls); i -= 1; parse_length = False
AttributeError: 'NoneType' object has no attribute 'edge_length'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
....
  File "/home/alfred/.local/lib/python3.6/site-packages/treeswift/Tree.py", line 1445, in read_tree_newick
    raise RuntimeError("Failed to parse string as Newick: %s"%ts)

I have attached a file that produces that error.
[error_treewick.txt](https://github.com/niemasd/TreeSwift/files/6351791/error_treewick.txt)

**Comment by niemasd** [comment]
This is an invalid Newick tree: parentheses (which are reserved symbols) are being used within labels (e.g. `ere(A)_2_A`), which is not allowed. If you replace the `(` and `)` symbols in your node labels with allowed symbols (e.g. `<` and `>`), it should work
