### ISSUE TITLE
Parsing Error - Unescaped Characters

### ISSUE THREAD

**Issue by valevalorin** [niemasd/TreeSwift#27]
I have a tree containing labels with both ';' and ':' characters. I can write the tree to the newick format without issue, but if I try to parse the string it fails when it encounters the unescaped ';' and ';' characters. I don't think there is a standard way of escaping for the format, but [this module](http://scikit-bio.org/docs/0.2.2/generated/skbio.io.newick.html#:~:text=To%20escape%20'%20use%20a%20preceding,COMMENT_CHARS%2C%20use%20a%20preceding%20'%20.) uses `'` as the escape characters.

**Comment by niemasd** [comment]
Can you provide an example file (ideally as small as possible) that I could use to test any potential fixes?

**Comment by valevalorin** [comment]
String:
`(https://youtube.com,&AMP;)root` || `('https://youtube.com','&AMP;')root` || `("https://youtube.com","&AMP;")root`

Code:
```
from treeswift import Node

root = Node('root')
url = Node('https://youtube.com')
amp = Node('&AMP;')
root.add_child(url)
root.add_child(amp)

t = treeswift.read_tree_newick(root.newick())
```

**Comment by niemasd** [comment]
Thanks for sharing! I don't think your original string is a valid Newick string, though: even with reserved characters being handled via escaping, Newick strings should end with a semicolon. The `TreeSwift.Node.newick` function is not meant to be called directly and is instead meant to be called recursively to generate the partial Newick string for a given subtree (so that `TreeSwift.Tree.newick` can just call `root.newick()` and then add a semicolon and some other stuff). Here's a slightly updated code example:

```python
from treeswift import Tree, Node
tree = Tree()
url = Node('https://youtube.com')
amp = Node('&AMP;')
tree.root.add_child(url)
tree.root.add_child(amp)
print(tree.newick())
```

Which outputs a Newick string that is "valid" if reserved symbols are allowed to be used if they're escaped:

```
[&R] (https://youtube.com,&AMP;);
```

This Newick string is indeed currently unsupported:

```python3
from treeswift import read_tree_newick
read_tree_newick("[&R] (https://youtube.com,&AMP;);")
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/treeswift/Tree.py", line 1445, in read_tree_newick
    n.edge_length = float(ls); i -= 1; parse_length = False
ValueError: could not convert string to float: '//youtube.com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/treeswift/Tree.py", line 1455, in read_tree_newick
    raise RuntimeError("Failed to parse string as Newick: %s"%ts)
RuntimeError: Failed to parse string as Newick: (https://youtube.com,&AMP;);
```

I'll try to add support for escaped reserved symbols as soon as possible

**Comment by valevalorin** [comment]
Your code sample is really interesting to me because it does something I couldn't find documentation of - how to make a tree manually (i.e. without reading it from a newick string). The process wasn't obvious, and I couldn't find an example, thus why I'm only creating nodes and getting the newick from there. 

I just double checked the Cookbook and I don't see an example like the above that shows the manual process. It might be a good idea to add it to the Cookbook as well.

**Comment by niemasd** [comment]
Regarding the code example, great idea! I've just added such a code sample to the Cookbook, under the following:

"TreeSwift also supports manually creating a tree from scratch:"

Regarding the initial issue, I just pushed a new release of TreeSwift (v1.1.31) which *should* fix the issue. I only support `'` (not `"`) to escape reserved symbols just as in the link you posted, but if the standard ever changes to support both, I'll update accordingly

**Comment by valevalorin** [comment]
Thank you so much!
