### ISSUE TITLE
node order in the preorder traversal

### ISSUE THREAD

**Issue by shayesteh99** [niemasd/TreeSwift#30]
Hi,

Thanks for the great package. An issue that I ran into recently was that the preorder traversal does not follow the node order that I expected it to follow, which is node, first child, second child. Since it uses the stack data structure, the actual order would be node, second child, first child. I was able to fix it by reversing the child orders in the preorder_traversal function. You can see my version below:

def traverse_preorder_correct(node, leaves=True, internal=True):
    '''Perform a preorder traversal starting at this ``Node`` object

    Args:
        ``leaves`` (``bool``): ``True`` to include leaves, otherwise ``False``

        ``internal`` (``bool``): ``True`` to include internal nodes, otherwise ``False``
    '''
    s = deque(); s.append(node)
    while len(s) != 0:
        n = s.pop()
        if (leaves and n.is_leaf()) or (internal and not n.is_leaf()):
            yield n
        s.extend(n.children[::-1])

I don't think that is a serious issue for most users, but since I had a list that was in this order and I wanted to match the tree branch lengths to the list, it took me a while to figure out what the issue was.

**Comment by niemasd** [comment]
Thanks for reaching out! Yes, exactly: TreeSwift pre-order traversal doesn't make any guarantees about order of child visit, just that parents are visited before children (and same for post-order, but that parent is visited after children)

If you're interested in doing a top-down traversal where nodes are visited in the order they appear in the `children` variable of their parent, you could use the level-order traversal implementation, which uses a Queue:

https://niema.net/TreeSwift/#treeswift.Tree.traverse_levelorder
